name: 'Terraform_remote_exec'

on:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3
      
     #### Checking terraform version
       
    - name: check terraform version
      run: terraform -v
      
     #### Initializing terraform
       
    - name: Terraform Init
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: terraform init
      
    - name: Terraform Plan done
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: terraform plan -input=false
      
     #### This Terraform apply will create vpc,ec2 instance 
     
    - name: Terraform apply
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
      run: |
 
       echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
       echo "Listing all file in curent directory:"
       pwd
       ls -ltr
       #terraform apply -auto-approve -input=false
